Mysql/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path, include
from . import views
from myauth.views import auth_login

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', views.index),
    re_path('^index/$', views.index),
    re_path('^accounts/login/$', auth_login),
    re_path('^', include(("myauth.urls", "myauth"), namespace="auth")),
    re_path('^', include(("software.urls", "software"), namespace="software")),
]

myauth/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path("auth/login/", views.auth_login, name="login"),
    re_path("auth/register/", views.auth_register, name="register"),
    re_path("auth/logout/", views.auth_logout, name="logout"),
]

software/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path("software/improve/", views.improve, name="improve"),
    re_path("software/sendcode/", views.sendcode, name="sendcode"),
    re_path("software/upgrade/", views.upgratesoft, name="upgrade"),
    re_path("software/save/", views.save, name="save"),
    re_path("software/myorder/", views.myorder, name="myorder"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/base.css">
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/base.js"></script>
    {% block link %}{% endblock %}
</head>
<body style="background-color: #F5F5F5">


<!--4.navbar-inverse 类可以改变导航条的外观-->
<div class="" style="background: yellow">
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" style="padding-left: 135px;padding-right: 135px">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index">主页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'software:improve' %}">功能改良</a>
                    </li>
                    <li>
                        <a href="#">软件定制</a>
                    </li>

                </ul>
                <form class="navbar-form navbar-left" method="get" action="#">
                    <div class="form-group">
                        <input type="text" name="key" class="form-control" placeholder="软件类别、名称"
                               {% if key %}value="{{ key }}" {% endif %}>
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>


                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">修改密码</a>
                            </li>
                            <li>
                                <a href="#">我的购物车</a>
                            </li>
                            <li>
                                <a href="{% url 'software:myorder' %}">我的订单</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">|</a>
                    </li>
                    <li>
                        <a href="{% url 'auth:logout' %}">注销</a>
                    </li>


                    {% else %}
                    <li>
                        <a href="{% url 'auth:login' %}">登录</a>
                    </li>
                    <li>
                        <a href="#">|</a>
                    </li>
                    <li>
                        <a href="{% url 'auth:register' %}">注册</a>
                    </li>
                    {% endif %}


                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</div>
{% block content %}{% endblock %}
<br>
<div style="background-color: white; height: 80px; line-height: 80px;text-align: center;">
    Copyright © 2018 ww All Rights Reserved.
</div>

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}主页{% endblock %}

{% block link %}
{% endblock %}

{% block content%}{%endblock%}